In [1]:
import pandas as pd
import os
import pathlib

In [2]:
# iterar sobre os arquivos CSV baixados e ler cada um deles
dfs = []
caminho_diretorio = 'datasets'
arquivos_csv = [f for f in os.listdir(caminho_diretorio) if f.endswith('.csv')]
for arquivo in arquivos_csv:
    caminho_arquivo = os.path.join(caminho_diretorio, arquivo)
    print(f"Lendo o arquivo: {caminho_arquivo}")
    df = pd.read_csv(caminho_arquivo, sep = '\t', encoding = 'utf-16')
    dfs.append(df)

Lendo o arquivo: datasets\Altamira - Cursos Livres _ 07_2026_Leads_2026-08-04_2026-08-04.csv
Lendo o arquivo: datasets\ALTAMIRA - Medicina - Trasf.Internacional 07_2026_Leads_2026-07-31_2026-08-03.csv
Lendo o arquivo: datasets\Altamira - Regulares _ TO 07_2026_Leads_2026-08-04_2026-08-04.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação Digital EAD_Leads_2022-08-19_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação EAD-copy_Leads_2022-07-05_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação EAD_Leads_2022-07-05_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação Presencial_Leads_2022-08-19_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação_Leads_2022-07-05_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Pós-Graduação_Leads_2022-07-05_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO] ALTAMIRA GRADUAÇÃO 09_2023-converted_Leads_2023-09-26_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO] ALTAMIRA GRADUAÇÃO 09_2023_Leads_2023-09-11_2026-08-03.csv
Lendo o arquivo: datasets\[PARETO] ALTAMIRA GRADUAÇÃO_Leads_2023-09-11_2026-08-03.csv

In [3]:
df = pd.concat(dfs, ignore_index=True)

In [4]:
df.columns

Index(['id', 'created_time', 'ad_id', 'ad_name', 'adset_id', 'adset_name',
       'campaign_id', 'campaign_name', 'form_id', 'form_name', 'is_organic',
       'platform', 'full_name', 'email', 'whatsapp_number',
       'eu_concordo_em_receber_comunicações', 'lead_status',
       'número_do_whatsapp', 'phone_number', 'inbox_url'],
      dtype='str')

In [5]:
dicionário_colunas = {
    
    'created_time': 'Criado em',
    'ad_id': 'ID Anúncio',
    'ad_name': 'Nome Anúncio',
    'adset_id': 'ID Conjunto de Anúncios',
    'adset_name': 'Nome do Conjunto de Anúncios',
    'campaign_id': 'ID da Campanha',
    'campaign_name': 'Nome da Campanha',
    'form_id': 'ID do Formulário',
    'form_name': 'Nome do Formulário',
    'is_organic': 'É Orgânico',
    'platform': 'Plataforma',
    'full_name': 'Nome Completo',
    'email': 'E-mail',
    'número_do_whatsapp': 'Número do WhatsApp',
    'eu_concordo_em_receber_comunicações': 'Concordo em Receber Comunicações',
    'phone_number': 'Telefone',
    'inbox_url': 'URL Caixa de Entrada'
}

In [6]:
# renomenar as colunas do DataFrame
df.rename(columns=dicionário_colunas, inplace=True)

In [7]:
df.head()

,id,Criado em,ID Anúncio,Nome Anúncio,ID Conjunto de Anúncios,Nome do Conjunto de Anúncios,ID da Campanha,Nome da Campanha,ID do Formulário,Nome do Formulário,É Orgânico,Plataforma,Nome Completo,E-mail,whatsapp_number,Concordo em Receber Comunicações,lead_status,Número do WhatsApp,Telefone,URL Caixa de Entrada
0,l:1729504458273828,2026-08-04T12:24:12-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,Ronald Melean,copameleanronald10@gmail.com,NaN,True,complete,5.917131e+10,NaN,NaN
1,l:1763490881334600,2026-08-04T07:51:22-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Ruth Tapia,rutina2112@gmail.com,NaN,True,complete,5.373012e+09,NaN,NaN
2,l:1365780821811795,2026-08-04T02:06:32-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Fernando Henrique de Oliveira Rodrigues,fernandohor1985@bol.com.br,NaN,True,complete,5.548000e+12,NaN,NaN
3,l:1410776137561685,2026-08-03T20:34:22-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Ruberth Adolfo Román Anez,ruberthadolfo@hotmail.com,NaN,True,complete,5.917844e+10,NaN,NaN
4,l:1700947347628738,2026-08-03T19:58:52-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Nad Aguilar,nadiraguilar22@gmail.com,NaN,True,complete,5.491166e+12,NaN,NaN

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 20 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                21 non-null     object
 1   Criado em                         21 non-null     object
 2   ID Anúncio                        21 non-null     object
 3   Nome Anúncio                      21 non-null     object
 4   ID Conjunto de Anúncios           21 non-null     object
 5   Nome do Conjunto de Anúncios      21 non-null     object
 6   ID da Campanha                    21 non-null     object
 7   Nome da Campanha                  21 non-null     object
 8   ID do Formulário                  21 non-null     object
 9   Nome do Formulário                21 non-null     object
 10  É Orgânico                        21 non-null     object
 11  Plataforma                        21 non-null     object
 12  Nome Completo                     21 non-null     object
 13  E-mail                            21 non-null     object
 14  whatsapp_number                   0 non-null      object
 15  Concordo em Receber Comunicações  21 non-null     object
 16  lead_status                       21 non-null     object
 17  Número do WhatsApp                21 non-null     float64
 18  Telefone                          0 non-null      object
 19  URL Caixa de Entrada              0 non-null      object
dtypes: float64(1), object(19)
memory usage: 3.4+ KB

In [9]:
df['Criado em'] = pd.to_datetime(df['Criado em'], format='ISO8601').dt.date

In [10]:
df['Telefone'] = df['Telefone'].astype(str).str.replace(r'\D', '', regex=True)

In [11]:
# exibir os leads criados hoje

hoje = pd.to_datetime('today').date()
df_hoje = df[df['Criado em'] == hoje]
df_hoje

,id,Criado em,ID Anúncio,Nome Anúncio,ID Conjunto de Anúncios,Nome do Conjunto de Anúncios,ID da Campanha,Nome da Campanha,ID do Formulário,Nome do Formulário,É Orgânico,Plataforma,Nome Completo,E-mail,whatsapp_number,Concordo em Receber Comunicações,lead_status,Número do WhatsApp,Telefone,URL Caixa de Entrada
0,l:1729504458273828,2026-08-04,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,Ronald Melean,copameleanronald10@gmail.com,NaN,True,complete,5.917131e+10,NaN,NaN
1,l:1763490881334600,2026-08-04,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Ruth Tapia,rutina2112@gmail.com,NaN,True,complete,5.373012e+09,NaN,NaN
2,l:1365780821811795,2026-08-04,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Fernando Henrique de Oliveira Rodrigues,fernandohor1985@bol.com.br,NaN,True,complete,5.548000e+12,NaN,NaN