In [1]:
import pandas as pd
import os
import pathlib

In [3]:
# iterar sobre os arquivos CSV baixados e ler cada um deles
dfs = []
caminho_diretorio = 'datasets'
arquivos_csv = [f for f in os.listdir(caminho_diretorio) if f.endswith('.csv')]
for arquivo in arquivos_csv:
    caminho_arquivo = os.path.join(caminho_diretorio, arquivo)
    print(f"Lendo o arquivo: {caminho_arquivo}")
    df = pd.read_csv(caminho_arquivo, sep = '\t', encoding = 'utf-16')
    dfs.append(df)

Lendo o arquivo: datasets\ALTAMIRA - Medicina - Trasf.Internacional 07_2026_Leads_2026-07-31_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação Digital EAD_Leads_2022-08-19_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação EAD-copy_Leads_2022-07-05_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação EAD_Leads_2022-07-05_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação Presencial_Leads_2022-08-19_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Graduação_Leads_2022-07-05_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO [ALTAMIRA] Pós-Graduação_Leads_2022-07-05_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO] ALTAMIRA GRADUAÇÃO 09_2023-converted_Leads_2023-09-26_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO] ALTAMIRA GRADUAÇÃO 09_2023_Leads_2023-09-11_2026-08-02.csv
Lendo o arquivo: datasets\[PARETO] ALTAMIRA GRADUAÇÃO_Leads_2023-09-11_2026-08-02.csv

In [4]:
df = pd.concat(dfs, ignore_index=True)

In [5]:
df.columns

Index(['id', 'created_time', 'ad_id', 'ad_name', 'adset_id', 'adset_name',
       'campaign_id', 'campaign_name', 'form_id', 'form_name', 'is_organic',
       'platform', 'full_name', 'email', 'número_do_whatsapp',
       'eu_concordo_em_receber_comunicações', 'lead_status', 'phone_number',
       'inbox_url'],
      dtype='str')

In [7]:
dicionário_colunas = {
    
    'created_time': 'Criado em',
    'ad_id': 'ID Anúncio',
    'ad_name': 'Nome Anúncio',
    'adset_id': 'ID Conjunto de Anúncios',
    'adset_name': 'Nome do Conjunto de Anúncios',
    'campaign_id': 'ID da Campanha',
    'campaign_name': 'Nome da Campanha',
    'form_id': 'ID do Formulário',
    'form_name': 'Nome do Formulário',
    'is_organic': 'É Orgânico',
    'platform': 'Plataforma',
    'full_name': 'Nome Completo',
    'email': 'E-mail',
    'número_do_whatsapp': 'Número do WhatsApp',
    'eu_concordo_em_receber_comunicações': 'Concordo em Receber Comunicações',
    'phone_number': 'Telefone',
    'inbox_url': 'URL Caixa de Entrada'
}

In [8]:
# renomenar as colunas do DataFrame
df.rename(columns=dicionário_colunas, inplace=True)

In [9]:
df.head()

,id,Criado em,ID Anúncio,Nome Anúncio,ID Conjunto de Anúncios,Nome do Conjunto de Anúncios,ID da Campanha,Nome da Campanha,ID do Formulário,Nome do Formulário,É Orgânico,Plataforma,Nome Completo,E-mail,Número do WhatsApp,Concordo em Receber Comunicações,lead_status,Telefone,URL Caixa de Entrada
0,l:1027848620141005,2026-08-03T15:12:16-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,Dhowgllas Elias,dhowgllas_elias@hotmail.com,5.582968e+11,True,complete,NaN,NaN
1,l:1525867905439976,2026-08-03T11:36:00-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Samuel Barbosa,gb.7@outlook.es,5.916052e+10,True,complete,NaN,NaN
2,l:2151836975376272,2026-08-03T08:25:54-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,Jhecys Gonçalves,jhecys@hotmail.com,5.916221e+10,True,complete,NaN,NaN
3,l:2477201022707487,2026-08-02T20:14:12-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Willian Anjos,wdos3-es@udabol.edu.bo,5.917456e+10,True,complete,NaN,NaN
4,l:1084170624184671,2026-08-02T18:53:18-03:00,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,nacho,ignacioramosmendoza17@gmail.com,5.917485e+10,True,complete,NaN,NaN

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 19 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                14 non-null     object
 1   Criado em                         14 non-null     object
 2   ID Anúncio                        14 non-null     object
 3   Nome Anúncio                      14 non-null     object
 4   ID Conjunto de Anúncios           14 non-null     object
 5   Nome do Conjunto de Anúncios      14 non-null     object
 6   ID da Campanha                    14 non-null     object
 7   Nome da Campanha                  14 non-null     object
 8   ID do Formulário                  14 non-null     object
 9   Nome do Formulário                14 non-null     object
 10  É Orgânico                        14 non-null     object
 11  Plataforma                        14 non-null     object
 12  Nome Completo                     14 non-null     object
 13  E-mail                            14 non-null     object
 14  Número do WhatsApp                14 non-null     float64
 15  Concordo em Receber Comunicações  14 non-null     object
 16  lead_status                       14 non-null     object
 17  Telefone                          0 non-null      object
 18  URL Caixa de Entrada              0 non-null      object
dtypes: float64(1), object(18)
memory usage: 2.2+ KB

In [15]:
df['Criado em'] = pd.to_datetime(df['Criado em'], format='ISO8601').dt.date

In [16]:
df['Telefone'] = df['Telefone'].astype(str).str.replace(r'\D', '', regex=True)

In [18]:
# exibir os anúncios criados hoje

hoje = pd.to_datetime('today').date()
df_hoje = df[df['Criado em'] == hoje]
df_hoje

,id,Criado em,ID Anúncio,Nome Anúncio,ID Conjunto de Anúncios,Nome do Conjunto de Anúncios,ID da Campanha,Nome da Campanha,ID do Formulário,Nome do Formulário,É Orgânico,Plataforma,Nome Completo,E-mail,Número do WhatsApp,Concordo em Receber Comunicações,lead_status,Telefone,URL Caixa de Entrada
0,l:1027848620141005,2026-08-03,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,Dhowgllas Elias,dhowgllas_elias@hotmail.com,5.582968e+11,True,complete,NaN,NaN
1,l:1525867905439976,2026-08-03,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,fb,Samuel Barbosa,gb.7@outlook.es,5.916052e+10,True,complete,NaN,NaN
2,l:2151836975376272,2026-08-03,ag:120259624112260537,Transf. Intern. | Banner | Homem e Mulher,as:120259603071030537,Lookalike Inscritos,c:120259603071040537,Pareto | Altamira | Lead ads | Medicina | 26.2...,f:27984430421196807,ALTAMIRA - Medicina - Trasf.Internacional 07/2026,False,ig,Jhecys Gonçalves,jhecys@hotmail.com,5.916221e+10,True,complete,NaN,NaN