In [11]:
import pandas as pd
import os
import pathlib

In [12]:
# iterar sobre os arquivos CSV baixados e ler cada um deles
dfs = []
caminho_diretorio = 'datasets'
arquivos_csv = [f for f in os.listdir(caminho_diretorio) if f.endswith('.csv')]
print(f"Lendo {len(arquivos_csv)} arquivos:")
for arquivo in arquivos_csv:
    caminho_arquivo = os.path.join(caminho_diretorio, arquivo)
    
    df = pd.read_csv(caminho_arquivo, sep = '\t', encoding = 'utf-16')
    dfs.append(df)

Lendo 58 arquivos:

In [13]:
df = pd.concat(dfs, ignore_index=True)

In [14]:
df.columns

Index(['id', 'created_time', 'ad_id', 'ad_name', 'adset_id', 'adset_name',
       'campaign_id', 'campaign_name', 'form_id', 'form_name', 'is_organic',
       'platform', 'qual_seu_curso_de_interesse?', 'nome_completo', 'email',
       'número_do_whatsapp', 'eu_concordo_em_receber_comunicações.',
       'lead_status', 'full_name', 'first_name', 'last_name', 'mobilephone',
       'eu_concordo_em_receber_comunicações', 'phone_number', 'telefone',
       'escolha_seu_curso'],
      dtype='str')

In [15]:
dicionário_colunas = {
    
    'created_time': 'Criado em',
    'ad_id': 'ID Anúncio',
    'ad_name': 'Nome Anúncio',
    'adset_id': 'ID Conjunto de Anúncios',
    'adset_name': 'Nome do Conjunto de Anúncios',
    'campaign_id': 'ID da Campanha',
    'campaign_name': 'Nome da Campanha',
    'form_id': 'ID do Formulário',
    'form_name': 'Nome do Formulário',
    'is_organic': 'É Orgânico',
    'platform': 'Plataforma',
    'full_name': 'Nome Completo',
    'email': 'E-mail',
    'número_do_whatsapp': 'Número do WhatsApp',
    'eu_concordo_em_receber_comunicações': 'Concordo em Receber Comunicações',
    'phone_number': 'Telefone',
    'inbox_url': 'URL Caixa de Entrada'
}

In [16]:
# renomenar as colunas do DataFrame
df.rename(columns=dicionário_colunas, inplace=True)

In [17]:
df.head()

Empty DataFrame
Columns: [id, Criado em, ID Anúncio, Nome Anúncio, ID Conjunto de Anúncios, Nome do Conjunto de Anúncios, ID da Campanha, Nome da Campanha, ID do Formulário, Nome do Formulário, É Orgânico, Plataforma, qual_seu_curso_de_interesse?, nome_completo, E-mail, Número do WhatsApp, eu_concordo_em_receber_comunicações., lead_status, Nome Completo, first_name, last_name, mobilephone, Concordo em Receber Comunicações, Telefone, telefone, escolha_seu_curso]
Index: []

[0 rows x 26 columns]

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 26 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   id                                    0 non-null      object
 1   Criado em                             0 non-null      object
 2   ID Anúncio                            0 non-null      object
 3   Nome Anúncio                          0 non-null      object
 4   ID Conjunto de Anúncios               0 non-null      object
 5   Nome do Conjunto de Anúncios          0 non-null      object
 6   ID da Campanha                        0 non-null      object
 7   Nome da Campanha                      0 non-null      object
 8   ID do Formulário                      0 non-null      object
 9   Nome do Formulário                    0 non-null      object
 10  É Orgânico                            0 non-null      object
 11  Plataforma                            0 non-null      object
 12  qual_seu_curso_de_interesse?          0 non-null      object
 13  nome_completo                         0 non-null      object
 14  E-mail                                0 non-null      object
 15  Número do WhatsApp                    0 non-null      object
 16  eu_concordo_em_receber_comunicações.  0 non-null      object
 17  lead_status                           0 non-null      object
 18  Nome Completo                         0 non-null      object
 19  first_name                            0 non-null      object
 20  last_name                             0 non-null      object
 21  mobilephone                           0 non-null      object
 22  Concordo em Receber Comunicações      0 non-null      object
 23  Telefone                              0 non-null      object
 24  telefone                              0 non-null      object
 25  escolha_seu_curso                     0 non-null      object
dtypes: object(26)
memory usage: 132.0+ bytes

In [19]:
df['Criado em'] = pd.to_datetime(df['Criado em'], format='ISO8601').dt.date

In [20]:
df['Telefone'] = df['Telefone'].astype(str).str.replace(r'\D', '', regex=True)

In [21]:
# exibir os leads criados hoje

hoje = pd.to_datetime('today').date()
df_hoje = df[df['Criado em'] == hoje]
df_hoje

Empty DataFrame
Columns: [id, Criado em, ID Anúncio, Nome Anúncio, ID Conjunto de Anúncios, Nome do Conjunto de Anúncios, ID da Campanha, Nome da Campanha, ID do Formulário, Nome do Formulário, É Orgânico, Plataforma, qual_seu_curso_de_interesse?, nome_completo, E-mail, Número do WhatsApp, eu_concordo_em_receber_comunicações., lead_status, Nome Completo, first_name, last_name, mobilephone, Concordo em Receber Comunicações, Telefone, telefone, escolha_seu_curso]
Index: []

[0 rows x 26 columns]